### Array

In [1]:
import numpy as np

In [2]:
simple_list=[4,5,6]
np.array(simple_list)

array([4, 5, 6])

In [4]:
ar=np.array([1,3,5,6])
ar

array([1, 3, 5, 6])

In [9]:
list_of_list=[1,3,5],[2,7,4],[3,6,9]
np.array(list_of_list)

array([[1, 3, 5],
       [2, 7, 4],
       [3, 6, 9]])

In [8]:
arr=np.array([[1,2,3],[7,5,9],[2,8,4]])
arr

array([[1, 2, 3],
       [7, 5, 9],
       [2, 8, 4]])

In [44]:
arr[2]=100
arr

array([[  1,   2,   3],
       [  7,   5,   9],
       [100, 100, 100]])

In [10]:
np.arange(3,100)

array([ 3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19,
       20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36,
       37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53,
       54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70,
       71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87,
       88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [11]:
np.arange(4,50,2)

array([ 4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36,
       38, 40, 42, 44, 46, 48])

In [12]:
np.zeros(6)

array([0., 0., 0., 0., 0., 0.])

In [13]:
np.zeros(6,dtype=int)

array([0, 0, 0, 0, 0, 0])

In [14]:
np.ones(4)

array([1., 1., 1., 1.])

In [15]:
np.ones(5,dtype=int)

array([1, 1, 1, 1, 1])

In [16]:
np.linspace(0,1,6)

array([0. , 0.2, 0.4, 0.6, 0.8, 1. ])

In [17]:
np.linspace(0,15,12)

array([ 0.        ,  1.36363636,  2.72727273,  4.09090909,  5.45454545,
        6.81818182,  8.18181818,  9.54545455, 10.90909091, 12.27272727,
       13.63636364, 15.        ])

In [18]:
np.eye(4,dtype=int)  ## Identity matrix

array([[1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1]])

In [20]:
np.random.rand(2,5)   ## Takes random value from 0 to 1

array([[0.77272507, 0.44867382, 0.73745613, 0.19505986, 0.95360913],
       [0.63073537, 0.5473212 , 0.65927649, 0.86847873, 0.82981374]])

In [21]:
np.random.randint(0,12,15)

array([ 8,  7,  3,  6,  1,  7,  4,  0,  3,  0,  9,  2,  3,  3, 11])

In [22]:
np.random.randn(2,5)

array([[-0.41894705,  1.47293821,  0.09144887,  0.06981758,  2.38882447],
       [-0.86806635,  0.92402785,  0.32423946, -0.88272174,  0.6675321 ]])

In [24]:
np.random.randint(2,50,64)

array([ 9, 38, 16, 16, 16, 49, 16, 40,  9, 28,  9, 21, 35, 23,  6, 29,  9,
       16,  7,  3, 48, 32, 23, 38, 45, 41, 22,  6, 37, 28, 23, 44, 39, 29,
       21, 28,  9, 49, 20,  7,  5, 16, 23, 10,  7, 28, 10, 30, 38, 32, 19,
       25, 40, 25, 47, 28, 42, 48, 38, 43, 49, 44, 39, 35])

In [26]:
sample_array=np.arange(2,12)
sample_array

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [27]:
sample_array.min()

2

In [28]:
sample_array.argmin()

0

In [32]:
rand_array=np.arange(0,10,2)
rand_array

array([0, 2, 4, 6, 8])

In [33]:
rand_array.min()

0

In [34]:
rand_array.argmin()

0

In [35]:
rand_array.argmax()

4

In [36]:
sample_array.dtype

dtype('int32')

In [37]:
rand_array.dtype

dtype('int32')

In [39]:
a=np.eye(6)
a

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

In [40]:
a=np.eye(5,dtype=int)  ## Identity Matrix

In [41]:
a

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

In [50]:
a=np.random.rand(2,3)
a

array([[0.33520029, 0.82354713, 0.7559905 ],
       [0.1674234 , 0.89026139, 0.22458037]])

In [51]:
a.T

array([[0.33520029, 0.1674234 ],
       [0.82354713, 0.89026139],
       [0.7559905 , 0.22458037]])

In [54]:
sample_array=np.arange(10,25)
sample_array

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24])

In [65]:
sample_array=sample_array.reshape(3,5)
sample_array

array([[10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [67]:
sample_array[0:1]

array([[10, 11, 12, 13, 14]])

In [68]:
sample_array[:]=222

In [69]:
sample_array

array([[222, 222, 222, 222, 222],
       [222, 222, 222, 222, 222],
       [222, 222, 222, 222, 222]])

### Two Dimentional Array

In [74]:
sample_matrix=np.array([[2,3,45],[6,8,9],[34,45,23],[24,45,32]])
sample_matrix

array([[ 2,  3, 45],
       [ 6,  8,  9],
       [34, 45, 23],
       [24, 45, 32]])

In [75]:
sample_matrix[2][2]

23

In [76]:
sample_matrix[1][2]

9

In [77]:
sample_matrix[:,2]

array([45,  9, 23, 32])

In [78]:
sample_matrix[1,1]

8

In [80]:
sample_matrix[0:2,0:2]

array([[2, 3],
       [6, 8]])

In [81]:
sample_matrix[1:,1:]

array([[ 8,  9],
       [45, 23],
       [45, 32]])

In [88]:
sample_matrix[2][2]

23