### Array & Numpy

In [1]:
import numpy as np

In [2]:
simple_list=[4,5,6]
np.array(simple_list)

array([4, 5, 6])

In [4]:
ar=np.array([1,3,5,6])
ar

array([1, 3, 5, 6])

In [9]:
list_of_list=[1,3,5],[2,7,4],[3,6,9]
np.array(list_of_list)

array([[1, 3, 5],
       [2, 7, 4],
       [3, 6, 9]])

In [8]:
arr=np.array([[1,2,3],[7,5,9],[2,8,4]])
arr

array([[1, 2, 3],
       [7, 5, 9],
       [2, 8, 4]])

In [44]:
arr[2]=100
arr

array([[  1,   2,   3],
       [  7,   5,   9],
       [100, 100, 100]])

In [10]:
np.arange(3,100)

array([ 3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19,
       20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36,
       37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53,
       54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70,
       71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87,
       88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [11]:
np.arange(4,50,2)

array([ 4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36,
       38, 40, 42, 44, 46, 48])

In [12]:
np.zeros(6)

array([0., 0., 0., 0., 0., 0.])

In [13]:
np.zeros(6,dtype=int)

array([0, 0, 0, 0, 0, 0])

In [14]:
np.ones(4)

array([1., 1., 1., 1.])

In [15]:
np.ones(5,dtype=int)

array([1, 1, 1, 1, 1])

In [16]:
np.linspace(0,1,6)

array([0. , 0.2, 0.4, 0.6, 0.8, 1. ])

In [17]:
np.linspace(0,15,12)

array([ 0.        ,  1.36363636,  2.72727273,  4.09090909,  5.45454545,
        6.81818182,  8.18181818,  9.54545455, 10.90909091, 12.27272727,
       13.63636364, 15.        ])

In [18]:
np.eye(4,dtype=int)  ## Identity matrix

array([[1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1]])

In [20]:
np.random.rand(2,5)   ## Takes random value from 0 to 1

array([[0.77272507, 0.44867382, 0.73745613, 0.19505986, 0.95360913],
       [0.63073537, 0.5473212 , 0.65927649, 0.86847873, 0.82981374]])

In [21]:
np.random.randint(0,12,15)

array([ 8,  7,  3,  6,  1,  7,  4,  0,  3,  0,  9,  2,  3,  3, 11])

In [22]:
np.random.randn(2,5)

array([[-0.41894705,  1.47293821,  0.09144887,  0.06981758,  2.38882447],
       [-0.86806635,  0.92402785,  0.32423946, -0.88272174,  0.6675321 ]])

In [24]:
np.random.randint(2,50,64)

array([ 9, 38, 16, 16, 16, 49, 16, 40,  9, 28,  9, 21, 35, 23,  6, 29,  9,
       16,  7,  3, 48, 32, 23, 38, 45, 41, 22,  6, 37, 28, 23, 44, 39, 29,
       21, 28,  9, 49, 20,  7,  5, 16, 23, 10,  7, 28, 10, 30, 38, 32, 19,
       25, 40, 25, 47, 28, 42, 48, 38, 43, 49, 44, 39, 35])

In [26]:
sample_array=np.arange(2,12)
sample_array

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [27]:
sample_array.min()

2

In [28]:
sample_array.argmin()

0

In [32]:
rand_array=np.arange(0,10,2)
rand_array

array([0, 2, 4, 6, 8])

In [33]:
rand_array.min()

0

In [34]:
rand_array.argmin()

0

In [35]:
rand_array.argmax()

4

In [36]:
sample_array.dtype

dtype('int32')

In [37]:
rand_array.dtype

dtype('int32')

In [39]:
a=np.eye(6)
a

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

In [40]:
a=np.eye(5,dtype=int)  ## Identity Matrix

In [41]:
a

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

In [50]:
a=np.random.rand(2,3)
a

array([[0.33520029, 0.82354713, 0.7559905 ],
       [0.1674234 , 0.89026139, 0.22458037]])

In [51]:
a.T

array([[0.33520029, 0.1674234 ],
       [0.82354713, 0.89026139],
       [0.7559905 , 0.22458037]])

In [54]:
sample_array=np.arange(10,25)
sample_array

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24])

In [65]:
sample_array=sample_array.reshape(3,5)
sample_array

array([[10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [67]:
sample_array[0:1]

array([[10, 11, 12, 13, 14]])

In [68]:
sample_array[:]=222

In [69]:
sample_array

array([[222, 222, 222, 222, 222],
       [222, 222, 222, 222, 222],
       [222, 222, 222, 222, 222]])

### Two Dimentional Array

In [74]:
sample_matrix=np.array([[2,3,45],[6,8,9],[34,45,23],[24,45,32]])
sample_matrix

array([[ 2,  3, 45],
       [ 6,  8,  9],
       [34, 45, 23],
       [24, 45, 32]])

In [75]:
sample_matrix[2][2]

23

In [76]:
sample_matrix[1][2]

9

In [77]:
sample_matrix[:,2]

array([45,  9, 23, 32])

In [78]:
sample_matrix[1,1]

8

In [80]:
sample_matrix[0:2,0:2]

array([[2, 3],
       [6, 8]])

In [81]:
sample_matrix[1:,1:]

array([[ 8,  9],
       [45, 23],
       [45, 32]])

In [88]:
sample_matrix[2][2]

23

In [25]:
import numpy as np

In [5]:
sample_array=np.arange(1,50)
sample_array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [6]:
sample_array + sample_array

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34,
       36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66, 68,
       70, 72, 74, 76, 78, 80, 82, 84, 86, 88, 90, 92, 94, 96, 98])

In [7]:
sample_array * sample_array

array([   1,    4,    9,   16,   25,   36,   49,   64,   81,  100,  121,
        144,  169,  196,  225,  256,  289,  324,  361,  400,  441,  484,
        529,  576,  625,  676,  729,  784,  841,  900,  961, 1024, 1089,
       1156, 1225, 1296, 1369, 1444, 1521, 1600, 1681, 1764, 1849, 1936,
       2025, 2116, 2209, 2304, 2401])

In [9]:
sample_array / sample_array

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [10]:
np.square(sample_array)

array([   1,    4,    9,   16,   25,   36,   49,   64,   81,  100,  121,
        144,  169,  196,  225,  256,  289,  324,  361,  400,  441,  484,
        529,  576,  625,  676,  729,  784,  841,  900,  961, 1024, 1089,
       1156, 1225, 1296, 1369, 1444, 1521, 1600, 1681, 1764, 1849, 1936,
       2025, 2116, 2209, 2304, 2401], dtype=int32)

In [11]:
np.log(sample_array)

array([0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791,
       1.79175947, 1.94591015, 2.07944154, 2.19722458, 2.30258509,
       2.39789527, 2.48490665, 2.56494936, 2.63905733, 2.7080502 ,
       2.77258872, 2.83321334, 2.89037176, 2.94443898, 2.99573227,
       3.04452244, 3.09104245, 3.13549422, 3.17805383, 3.21887582,
       3.25809654, 3.29583687, 3.33220451, 3.36729583, 3.40119738,
       3.4339872 , 3.4657359 , 3.49650756, 3.52636052, 3.55534806,
       3.58351894, 3.61091791, 3.63758616, 3.66356165, 3.68887945,
       3.71357207, 3.73766962, 3.76120012, 3.78418963, 3.80666249,
       3.8286414 , 3.8501476 , 3.87120101, 3.8918203 ])

In [12]:
np.exp(sample_array)

array([2.71828183e+00, 7.38905610e+00, 2.00855369e+01, 5.45981500e+01,
       1.48413159e+02, 4.03428793e+02, 1.09663316e+03, 2.98095799e+03,
       8.10308393e+03, 2.20264658e+04, 5.98741417e+04, 1.62754791e+05,
       4.42413392e+05, 1.20260428e+06, 3.26901737e+06, 8.88611052e+06,
       2.41549528e+07, 6.56599691e+07, 1.78482301e+08, 4.85165195e+08,
       1.31881573e+09, 3.58491285e+09, 9.74480345e+09, 2.64891221e+10,
       7.20048993e+10, 1.95729609e+11, 5.32048241e+11, 1.44625706e+12,
       3.93133430e+12, 1.06864746e+13, 2.90488497e+13, 7.89629602e+13,
       2.14643580e+14, 5.83461743e+14, 1.58601345e+15, 4.31123155e+15,
       1.17191424e+16, 3.18559318e+16, 8.65934004e+16, 2.35385267e+17,
       6.39843494e+17, 1.73927494e+18, 4.72783947e+18, 1.28516001e+19,
       3.49342711e+19, 9.49611942e+19, 2.58131289e+20, 7.01673591e+20,
       1.90734657e+21])

In [13]:
np.sqrt(sample_array)

array([1.        , 1.41421356, 1.73205081, 2.        , 2.23606798,
       2.44948974, 2.64575131, 2.82842712, 3.        , 3.16227766,
       3.31662479, 3.46410162, 3.60555128, 3.74165739, 3.87298335,
       4.        , 4.12310563, 4.24264069, 4.35889894, 4.47213595,
       4.58257569, 4.69041576, 4.79583152, 4.89897949, 5.        ,
       5.09901951, 5.19615242, 5.29150262, 5.38516481, 5.47722558,
       5.56776436, 5.65685425, 5.74456265, 5.83095189, 5.91607978,
       6.        , 6.08276253, 6.164414  , 6.244998  , 6.32455532,
       6.40312424, 6.4807407 , 6.55743852, 6.63324958, 6.70820393,
       6.78232998, 6.8556546 , 6.92820323, 7.        ])

In [14]:
np.max(sample_array)

49

In [15]:
np.argmax(sample_array)

48

In [16]:
np.min(sample_array)

1

In [17]:
np.std(sample_array)

14.142135623730951

In [18]:
np.var(sample_array)

200.0

In [19]:
np.mean(sample_array)

25.0

In [20]:
array=np.random.randn(3,5)  #Normal distribution
array

array([[-1.67084953, -0.54344171, -0.62510815,  0.7353294 ,  0.89298713],
       [ 1.54800839,  0.01629737,  0.43382089,  1.17450126,  0.33580143],
       [-0.68071398, -1.18620463,  0.39695875, -1.52092117,  0.81991001]])

In [21]:
np.round(array,decimals=3)

array([[-1.671, -0.543, -0.625,  0.735,  0.893],
       [ 1.548,  0.016,  0.434,  1.175,  0.336],
       [-0.681, -1.186,  0.397, -1.521,  0.82 ]])

In [29]:
sports=np.array(['cricket','football','volleyball','cricket'])
sports=np.unique(sports)
sports

array(['cricket', 'football', 'volleyball'], dtype='<U10')